# Generated by Django 4.0.3 on 2022-03-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myphotos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
